### ISSUE TITLE
Migrate from System.Drawing.Common

### ISSUE THREAD

**Issue by adamshakhabov** [ShapeCrawler/ShapeCrawler#184]
Migrate from `System.Drawing.Common` to `ImageSharp`, `SkiaSharp` or `Microsoft.Maui.Graphics` to be able to set .NET 6 target.

## Tasks
- [x] convert color name to HEX
- [x] refactor text fit
- [x] refactor converting EMU to pixel

## Useful links:

- https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action
