### ISSUE TITLE
Can I change the Min/Max of BarChart axis?

### ISSUE THREAD

**Issue by blafa** [ShapeCrawler/ShapeCrawler#482]
Hi

I love ShapeCrawler :) Is it possible to change Min/Max of BarCharts axis?

**Comment by adamshakhabov** [comment]
Hello,

thank you for the feedback🙂

No, it is not possible. But it is a good idea, I will check what we can do.

**Comment by adamshakhabov** [comment]
- [ ] Read Minimum/Maximum
- [ ] Update Minimum/Maximum
- [ ] Add Bar Chart
